### ISSUE TITLE
invalid version number

### ISSUE THREAD

**Issue by ivandgreat** [Zorlin/netbox-windows#1]
hello.. im trying to install this on my window 10 OS. When migrating the i have an error below..

Applying extras.0008_reports...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", li                                                           ne 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", li                                                           ne 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 2                                                           83, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 3                                                           30, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/migrate                                                           .py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line                                                            115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_i                                                           nitial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line                                                            145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_                                                           initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line                                                            244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/migration.py", lin                                                           e 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, projec                                                           t_state)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/operations/special                                                           .py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/cygdrive/c/netbox/current/netbox/extras/migrations/0008_reports.py", li                                                           ne 22, in verify_postgresql_version
    if StrictVersion(pg_version) < StrictVersion('9.4.0'):
  File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '9.6.5,'

Please need your support how to fix this. Thanks.

**Comment by Zorlin** [comment]
Hi there,

Unfortunately I haven't had time to work on this project much lately, and it is made kind of irrelevant by the Docker version of Netbox.

If you need to run Netbox on Windows, I would suggest using the Docker method instead of NFW.
